spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 20000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_USERNAME}
    name: BillShare App
    baseUrlGroupMember: ${APP_FRONTEND_URL}/group-member/
    baseUrlFriendShip: ${APP_FRONTEND_URL}/friends/
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    default-encoding: UTF-8

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0
jwt:
  timeOutAccessToken: 5
  timeOutRefreshToken: 1440
  secretKeyAccessToken: ${JWT_SECRET_ACCESS}
  secretKeyRefreshToken: ${JWT_SECRET_REFRESH}
  secretKeyFriendship: ${JWT_SECRET_FRIENDSHIP};
  secretKeyOtp: ${JWT_SECRET_OTP};
app:
  otp:
    expiration:
      minutes: 5
    cooldown:
      seconds: 60
    max-retries: 5




