spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
    username: postgres.yulezlspzgdnbxunutqm
    password: 'Giang@19102004'
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 20000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sendgrid:
    api-key: ${API_KEY}
    from-email: nguyenkimgiang489@gmail.com
    name: BillShare
    templateConfirmParticipationId: d-5c76fa0599a24120bcb98560667202a0
    baseUrl: http://localhost:3000/group-member/


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0
jwt:
  timeOutAccessToken: 5
  timeOutRefreshToken: 1440
  secretKeyAccessToken: jkbJytBJPN9ML9pGNX73yFEpoUbKEgpBbnDe9+vHo8o=
  secretKeyRefreshToken: 6sLRRGxtFgPyxLGFuQFuhPlACKs83VabaQ4sIS1X7Rc=

