spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:

    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
    username: postgres.yulezlspzgdnbxunutqm
    password: 'Giang@19102004'
    driver-class-name: org.postgresql.Driver


    hikari: # Connection poll
      max-lifetime: 300000      # 5 phút
      idle-timeout: 60000       # 1 phút
      validation-timeout: 5000  # 5 giây
      minimum-idle: 5
      maximum-pool-size: 20

  spring:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0
jwt:
  timeOutAccessToken: 1
  timeOutRefreshToken: 1440
  secretKeyAccessToken: jkbJytBJPN9ML9pGNX73yFEpoUbKEgpBbnDe9+vHo8o=
  secretKeyRefreshToken: 6sLRRGxtFgPyxLGFuQFuhPlACKs83VabaQ4sIS1X7Rc=

