spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 20000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: nguyenkimgiang489@gmail.com
    name: BillShare
    templateConfirmParticipationId: d-5c76fa0599a24120bcb98560667202a0
    baseUrl: http://localhost:3000/group-member/


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0
jwt:
  timeOutAccessToken: 5
  timeOutRefreshToken: 1440
  secretKeyAccessToken: ${JWT_SECRET_ACCESS}
  secretKeyRefreshToken: ${JWT_SECRET_REFRESH}

